title:        101
url:          http://101.apievangelist.com
logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-101.png
logo_width:   80
logo_bottom_padding: 0

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/news/page:num"

production_url : http://101.apievangelist.com

BASE_PATH : http://101.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html

# Masthead title
masthead_link: http://101.apievangelist.com
masthead_font_size: 90
masthead_title: '{"API 101"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45

# Navigation
navigation:
  - label1: API 101 - Provide >>
    link1: /index.html
    size1: 100
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 100
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 25
sponsors_padding_top: 10
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json
